# Generated by Django 4.0.6 on 2022-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='level',
            new_name='alias',
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.TextField(max_length=250),
        ),
    ]
